# Loops

Topics:
1. `while` loops
2. `for` loops
<br>

## while loops

The syntax for a `while` is

```julia
while *condition*
    *loop body*
end
```

For example, we could use `while` to count or to iterate over an array.

In [2]:
i=0
for j in 1:5
    i=i+1
end
i

5

## for loops

The syntax for a `for` loop is

```julia
for *var* in *loop iterable*
    *loop body*
end
```

We could use a for loop to generate the same results as either of the examples above:

In [3]:
for s in "string"
    println(s)
end

s
t
r
i
n
g


Now let's use `for` loops to create some addition tables, where the value of every entry is the sum of its row and column indices. <br>

First, we initialize an array with zeros.

In [4]:
a=zeros(4,4)

4×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

Here's some syntactic sugar for the same nested `for` loop

In [9]:
#for (i,j) in zip(1:size(a)[1],1:size(a)[2])
for i in 1:size(a)[1]
    for j in 1:size(a)[2]
        a[i,j]=i*j
    end
end
a

4×4 Array{Float64,2}:
 1.0  2.0   3.0   4.0
 2.0  4.0   6.0   8.0
 3.0  6.0   9.0  12.0
 4.0  8.0  12.0  16.0

In [11]:
for i in 1:length(a)
    a[i]=i
end
a

4×4 Array{Float64,2}:
 1.0  5.0   9.0  13.0
 2.0  6.0  10.0  14.0
 3.0  7.0  11.0  15.0
 4.0  8.0  12.0  16.0

The more "Julia" way to create this addition table would have been with an *array comprehension*.

In [13]:
[2^i for i in 1:10]

10-element Array{Int64,1}:
    2
    4
    8
   16
   32
   64
  128
  256
  512
 1024

### Exercises

#### 4.1 
Loop over integers between 1 and 100 and print their squares.

In [16]:
squares=Dict{Int64,Int64}()
for i in 1:10
    squares[i] = i^2
end
squares

Dict{Int64,Int64} with 10 entries:
  7  => 49
  4  => 16
  9  => 81
  10 => 100
  2  => 4
  3  => 9
  5  => 25
  8  => 64
  6  => 36
  1  => 1

#### 4.2 
Add to the code above a bit to create a dictionary, `squares` that holds integers and their squares as key, value pairs such that

```julia
squares[10] == 100
```

#### 4.3 
Use an array comprehension to create an an array `squares_arr` that stores the squares for all integers between 1 and 100.

In [17]:
squares_arr =[i^2 for i in 1:100]

100-element Array{Int64,1}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

Please click on `Validate` on the top, once you are done with the exercises.